[package]
name = "colette-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
colette-crud.workspace = true
colette-handler.workspace = true
colette-http.workspace = true
colette-ingestion.workspace = true
colette-plugins.workspace = true
colette-queue.workspace = true
colette-repository.workspace = true
colette-s3.workspace = true
colette-scraper.workspace = true
colette-smtp.workspace = true
config.workspace = true
cron = { version = "0.15.0", default-features = false }
futures.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tower = { version = "0.5.2", default-features = false, features = [
  "buffer",
  "limit",
  "tracing",
] }
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
url.workspace = true
