[package]
name = "colette-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono.workspace = true
cron = { version = "0.13", default-features = false }
tokio.workspace = true
tower.workspace = true
tracing.workspace = true
