/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as PrivateImport } from './routes/_private'
import { Route as PrivateIndexImport } from './routes/_private/index'
import { Route as PrivateFeedsImport } from './routes/_private/feeds'
import { Route as PrivateBookmarksImport } from './routes/_private/bookmarks'
import { Route as PrivateFeedsIndexImport } from './routes/_private/feeds/index'
import { Route as PrivateBookmarksIndexImport } from './routes/_private/bookmarks/index'
import { Route as PrivateFeedsArchivedImport } from './routes/_private/feeds/archived'
import { Route as PrivateFeedsIdImport } from './routes/_private/feeds/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const PrivateIndexRoute = PrivateIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateFeedsRoute = PrivateFeedsImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateBookmarksRoute = PrivateBookmarksImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateFeedsIndexRoute = PrivateFeedsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateFeedsRoute,
} as any)

const PrivateBookmarksIndexRoute = PrivateBookmarksIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateBookmarksRoute,
} as any)

const PrivateFeedsArchivedRoute = PrivateFeedsArchivedImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => PrivateFeedsRoute,
} as any)

const PrivateFeedsIdRoute = PrivateFeedsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PrivateFeedsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_private/bookmarks': {
      id: '/_private/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof PrivateBookmarksImport
      parentRoute: typeof PrivateImport
    }
    '/_private/feeds': {
      id: '/_private/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof PrivateFeedsImport
      parentRoute: typeof PrivateImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/feeds/$id': {
      id: '/_private/feeds/$id'
      path: '/$id'
      fullPath: '/feeds/$id'
      preLoaderRoute: typeof PrivateFeedsIdImport
      parentRoute: typeof PrivateFeedsImport
    }
    '/_private/feeds/archived': {
      id: '/_private/feeds/archived'
      path: '/archived'
      fullPath: '/feeds/archived'
      preLoaderRoute: typeof PrivateFeedsArchivedImport
      parentRoute: typeof PrivateFeedsImport
    }
    '/_private/bookmarks/': {
      id: '/_private/bookmarks/'
      path: '/'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof PrivateBookmarksIndexImport
      parentRoute: typeof PrivateBookmarksImport
    }
    '/_private/feeds/': {
      id: '/_private/feeds/'
      path: '/'
      fullPath: '/feeds/'
      preLoaderRoute: typeof PrivateFeedsIndexImport
      parentRoute: typeof PrivateFeedsImport
    }
  }
}

// Create and export the route tree

interface PrivateBookmarksRouteChildren {
  PrivateBookmarksIndexRoute: typeof PrivateBookmarksIndexRoute
}

const PrivateBookmarksRouteChildren: PrivateBookmarksRouteChildren = {
  PrivateBookmarksIndexRoute: PrivateBookmarksIndexRoute,
}

const PrivateBookmarksRouteWithChildren =
  PrivateBookmarksRoute._addFileChildren(PrivateBookmarksRouteChildren)

interface PrivateFeedsRouteChildren {
  PrivateFeedsIdRoute: typeof PrivateFeedsIdRoute
  PrivateFeedsArchivedRoute: typeof PrivateFeedsArchivedRoute
  PrivateFeedsIndexRoute: typeof PrivateFeedsIndexRoute
}

const PrivateFeedsRouteChildren: PrivateFeedsRouteChildren = {
  PrivateFeedsIdRoute: PrivateFeedsIdRoute,
  PrivateFeedsArchivedRoute: PrivateFeedsArchivedRoute,
  PrivateFeedsIndexRoute: PrivateFeedsIndexRoute,
}

const PrivateFeedsRouteWithChildren = PrivateFeedsRoute._addFileChildren(
  PrivateFeedsRouteChildren,
)

interface PrivateRouteChildren {
  PrivateBookmarksRoute: typeof PrivateBookmarksRouteWithChildren
  PrivateFeedsRoute: typeof PrivateFeedsRouteWithChildren
  PrivateIndexRoute: typeof PrivateIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateBookmarksRoute: PrivateBookmarksRouteWithChildren,
  PrivateFeedsRoute: PrivateFeedsRouteWithChildren,
  PrivateIndexRoute: PrivateIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/bookmarks': typeof PrivateBookmarksRouteWithChildren
  '/feeds': typeof PrivateFeedsRouteWithChildren
  '/': typeof PrivateIndexRoute
  '/feeds/$id': typeof PrivateFeedsIdRoute
  '/feeds/archived': typeof PrivateFeedsArchivedRoute
  '/bookmarks/': typeof PrivateBookmarksIndexRoute
  '/feeds/': typeof PrivateFeedsIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof PrivateIndexRoute
  '/feeds/$id': typeof PrivateFeedsIdRoute
  '/feeds/archived': typeof PrivateFeedsArchivedRoute
  '/bookmarks': typeof PrivateBookmarksIndexRoute
  '/feeds': typeof PrivateFeedsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_private': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/_private/bookmarks': typeof PrivateBookmarksRouteWithChildren
  '/_private/feeds': typeof PrivateFeedsRouteWithChildren
  '/_private/': typeof PrivateIndexRoute
  '/_private/feeds/$id': typeof PrivateFeedsIdRoute
  '/_private/feeds/archived': typeof PrivateFeedsArchivedRoute
  '/_private/bookmarks/': typeof PrivateBookmarksIndexRoute
  '/_private/feeds/': typeof PrivateFeedsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/bookmarks'
    | '/feeds'
    | '/'
    | '/feeds/$id'
    | '/feeds/archived'
    | '/bookmarks/'
    | '/feeds/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/feeds/$id'
    | '/feeds/archived'
    | '/bookmarks'
    | '/feeds'
  id:
    | '__root__'
    | '/_private'
    | '/login'
    | '/_private/bookmarks'
    | '/_private/feeds'
    | '/_private/'
    | '/_private/feeds/$id'
    | '/_private/feeds/archived'
    | '/_private/bookmarks/'
    | '/_private/feeds/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_private",
        "/login"
      ]
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/bookmarks",
        "/_private/feeds",
        "/_private/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_private/bookmarks": {
      "filePath": "_private/bookmarks.tsx",
      "parent": "/_private",
      "children": [
        "/_private/bookmarks/"
      ]
    },
    "/_private/feeds": {
      "filePath": "_private/feeds.tsx",
      "parent": "/_private",
      "children": [
        "/_private/feeds/$id",
        "/_private/feeds/archived",
        "/_private/feeds/"
      ]
    },
    "/_private/": {
      "filePath": "_private/index.tsx",
      "parent": "/_private"
    },
    "/_private/feeds/$id": {
      "filePath": "_private/feeds/$id.tsx",
      "parent": "/_private/feeds"
    },
    "/_private/feeds/archived": {
      "filePath": "_private/feeds/archived.tsx",
      "parent": "/_private/feeds"
    },
    "/_private/bookmarks/": {
      "filePath": "_private/bookmarks/index.tsx",
      "parent": "/_private/bookmarks"
    },
    "/_private/feeds/": {
      "filePath": "_private/feeds/index.tsx",
      "parent": "/_private/feeds"
    }
  }
}
ROUTE_MANIFEST_END */
