[package]
name = "colette-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
chrono.workspace = true
libsql.workspace = true
serde.workspace = true
torii-core = { git = "https://github.com/cmackenzie1/torii-rs", default-features = false }
