[package]
name = "colette-session"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
tower-sessions-core = { version = "0.13", default-features = false, features = [
  "deletion-task",
] }
tower-sessions-sqlx-store = { version = "0.14", default-features = false }

[features]
default = []
postgres = ["tower-sessions-sqlx-store/postgres"]
sqlite = ["tower-sessions-sqlx-store/sqlite"]
