[package]
name = "colette-session"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
colette-postgres = { workspace = true, optional = true }
colette-sqlite = { workspace = true, optional = true }
tower-sessions-core = { version = "0.13", default-features = false, features = [
  "deletion-task",
] }

[features]
default = []
postgres = ["dep:colette-postgres"]
sqlite = ["dep:colette-sqlite"]
