[workspace]
members = [
  "apps/server",
  "crates/api",
  "crates/core",
  "crates/feed",
  "crates/http",
  "crates/job",
  "crates/meta",
  "crates/migration",
  "crates/netscape",
  "crates/opml",
  "crates/plugins",
  "crates/query",
  "crates/queue",
  "crates/repository",
  "crates/scraper",
  "crates/storage",
  "crates/util",
]
resolver = "2"

[workspace.dependencies]
async-trait = { version = "0.1.85", default-features = false }
axum = { version = "0.8.1", default-features = false, features = [
  "http1",
  "json",
  "query",
  "macros",
] }
bytes = { version = "1.9.0", default-features = false }
chrono = { version = "0.4.39", default-features = false, features = [
  "clock",
  "serde",
  "std",
] }
colette-api.path = "crates/api"
colette-core.path = "crates/core"
colette-feed.path = "crates/feed"
colette-http.path = "crates/http"
colette-job.path = "crates/job"
colette-meta.path = "crates/meta"
colette-migration.path = "crates/migration"
colette-netscape.path = "crates/netscape"
colette-opml.path = "crates/opml"
colette-plugins.path = "crates/plugins"
colette-query.path = "crates/query"
colette-queue.path = "crates/queue"
colette-repository.path = "crates/repository"
colette-scraper.path = "crates/scraper"
colette-storage.path = "crates/storage"
colette-util.path = "crates/util"
deadpool-postgres = { version = "0.14.1", default-features = false, features = [
  "serde",
] }
futures = { version = "0.3.31", default-features = false }
html5gum = { version = "0.7.0", default-features = false }
http = { version = "1.2.0", default-features = false }
http-body-util = { version = "0.1.2", default-features = false }
jsonwebtoken = { version = "9.3.1", default-features = false }
quick-xml = { version = "0.37.2", default-features = false }
reqwest = { version = "0.12.12", default-features = false, features = [
  "http2",
] }
rust-s3 = { version = "0.36.0-beta.2", default-features = false, features = [
  "fail-on-err",
] }
scraper = { version = "0.23.1", default-features = false }
sea-query = { version = "0.32.2", default-features = false, features = [
  "backend-postgres",
  "with-chrono",
  "with-json",
  "with-uuid",
] }
serde = { version = "1.0.217", default-features = false }
serde_json = { version = "1.0.135", default-features = false, features = [
  "std",
] }
thiserror = { version = "2.0.11", default-features = false }
time = { version = "0.3.39", default-features = false, features = ["serde"] }
tokio = { version = "1.43.0", default-features = false, features = ["macros"] }
tokio-postgres = { version = "0.7.13", default-features = false, features = [
  "with-chrono-0_4",
  "with-serde_json-1",
  "with-uuid-1",
] }
tower = { version = "0.5.2", default-features = false }
tower-http = { version = "0.6.2", default-features = false, features = [
  "cors",
  "trace",
] }
tracing = { version = "0.1.41", default-features = false }
url = { version = "2.5.4", default-features = false, features = ["serde"] }
uuid = { version = "1.11.1", default-features = false, features = [
  "serde",
  "std",
  "v4",
] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
