[workspace]
members = [
  "crates/api",
  "crates/backup",
  "crates/config",
  "crates/core",
  "crates/db",
  "crates/entities",
  "crates/migrations",
  "crates/password",
  "crates/plugins",
  "crates/scraper",
  "crates/server",
  "crates/tasks",
  "crates/ui",
]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1", default-features = false, features = ["std"] }
async-trait = { version = "0.1", default-features = false }
axum = { version = "0.7", default-features = false, features = [
  "http1",
  "macros",
  "multipart",
  "tokio",
] }
chrono = { version = "0.4", default-features = false, features = ["serde"] }
colette-api.path = "crates/api"
colette-backup.path = "crates/backup"
colette-config.path = "crates/config"
colette-core.path = "crates/core"
colette-db.path = "crates/db"
colette-entities.path = "crates/entities"
colette-migrations.path = "crates/migrations"
colette-password.path = "crates/password"
colette-plugins.path = "crates/plugins"
colette-scraper.path = "crates/scraper"
colette-tasks.path = "crates/tasks"
futures = { version = "0.3", default-features = false }
http = { version = "1", default-features = false, features = ["std"] }
lazy-regex = { version = "3", default-features = false, features = [
  "std",
  "perf",
] }
quick-xml = { version = "0.36", features = ["overlapped-lists", "serialize"] }
sea-orm = { version = "1.1.0-rc.1", default-features = false, features = [
  "macros",
  "sqlx-postgres",
  "sqlx-sqlite",
  "with-chrono",
  "with-uuid",
] }
serde = { version = "1", default-features = false }
strum = { version = "0.26", default-features = false }
strum_macros = { version = "0.26", default-features = false }
thiserror = { version = "1", default-features = false }
tokio = { version = "1", default-features = false, features = [
  "macros",
  "rt-multi-thread",
] }
tower = { version = "0.4", default-features = false }
tower-http = { version = "0.5", default-features = false, features = [
  "cors",
  "fs",
] }
tracing = { version = "0.1", default-features = false }
url = { version = "2", default-features = false, features = ["serde"] }
uuid = { version = "1", default-features = false, features = ["serde", "v4"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true

[profile.wasm-release]
inherits = "release"
