[workspace]
members = [
  "apps/server",
  "crates/core",
  "crates/feed",
  "crates/http",
  "crates/meta",
  "crates/netscape",
  "crates/opml",
  "crates/plugins",
  "crates/util",
]
resolver = "2"

[workspace.dependencies]
apalis-redis = { version = "0.6.4", default-features = false, features = [
  "tokio-comp",
] }
async-trait = { version = "0.1.85", default-features = false }
bytes = { version = "1.9.0", default-features = false }
chrono = { version = "0.4.39", default-features = false, features = [
  "clock",
  "serde",
  "std",
] }
colette-core.path = "crates/core"
colette-feed.path = "crates/feed"
colette-http.path = "crates/http"
colette-meta.path = "crates/meta"
colette-netscape.path = "crates/netscape"
colette-opml.path = "crates/opml"
colette-plugins.path = "crates/plugins"
colette-util.path = "crates/util"
futures = { version = "0.3.31", default-features = false }
html5gum = { version = "0.7.0", default-features = false }
http = { version = "1.2.0", default-features = false }
http-body-util = { version = "0.1.2", default-features = false }
object_store = { version = "0.11.2", default-features = false, features = [
  "aws",
  "tls-webpki-roots",
] }
quick-xml = { version = "0.37.2", default-features = false }
reqwest = { version = "0.12.12", default-features = false, features = [
  "http2",
  "rustls-tls-webpki-roots",
] }
scraper = { version = "0.22.0", default-features = false }
serde = { version = "1.0.217", default-features = false }
serde_json = { version = "1.0.135", default-features = false, features = [
  "std",
] }
sqlx = { version = "0.8.3", features = [
  "chrono",
  "json",
  "macros",
  "migrate",
  "postgres",
  "runtime-tokio",
  "tls-rustls-ring-webpki",
  "uuid",
] }
thiserror = { version = "2.0.11", default-features = false }
tokio = { version = "1.43.0", default-features = false, features = [
  "macros",
  "rt-multi-thread",
] }
url = { version = "2.5.4", default-features = false, features = ["serde"] }
uuid = { version = "1.11.1", default-features = false, features = [
  "serde",
  "v4",
] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
