[workspace]
members = [
  "crates/backup",
  "crates/config",
  "crates/core",
  "crates/database",
  "crates/password",
  "crates/plugins",
  "crates/postgres",
  "crates/scraper",
  "crates/server",
  "crates/sqlite",
  "crates/tasks",
]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0.86", default-features = false, features = ["std"] }
async-trait = { version = "0.1.80", default-features = false }
chrono = { version = "0.4.38", default-features = false }
colette-backup.path = "crates/backup"
colette-config.path = "crates/config"
colette-core.path = "crates/core"
colette-database.path = "crates/database"
colette-password.path = "crates/password"
colette-plugins.path = "crates/plugins"
colette-postgres.path = "crates/postgres"
colette-scraper.path = "crates/scraper"
colette-sqlite.path = "crates/sqlite"
colette-tasks.path = "crates/tasks"
futures = { version = "0.3.30", default-features = false }
http = { version = "1.1.0", default-features = false, features = ["std"] }
lazy-regex = { version = "3.1.0", default-features = false, features = [
  "lite",
] }
serde = { version = "1.0.203", default-features = false }
thiserror = { version = "1.0.61", default-features = false }
tokio = { version = "1.38.1", default-features = false, features = [
  "macros",
  "rt-multi-thread",
] }
url = { version = "2.5.2", default-features = false }
uuid = { version = "1.10.0", default-features = false }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = true
