[workspace]
members = [
  "apps/cloudflare",
  # "apps/desktop/src-tauri",
  # "apps/leptos",
  "apps/server",

  "crates/api",
  "crates/backup",
  "crates/config",
  "crates/core",
  "crates/feed",
  "crates/http",
  "crates/meta",
  "crates/migration",
  "crates/netscape",
  "crates/opml",
  "crates/plugins",
  "crates/queue",
  "crates/repository",
  "crates/scraper",
  "crates/session",
  "crates/task",
  "crates/util",
  "crates/worker",
]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0.95", default-features = false, features = ["std"] }
async-trait = { version = "0.1.85", default-features = false }
axum = { version = "0.8.1", default-features = false, features = [
  "http1",
  "json",
  "query",
  "macros",
] }
axum-embed = { version = "0.1.0", default-features = false }
axum-extra = { version = "0.10.0", default-features = false, features = [
  "query",
  "tracing",
] }
bytes = { version = "1.9.0", default-features = false }
chrono = { version = "0.4.39", default-features = false, features = [
  "clock",
  "serde",
  "std",
] }
colette-api.path = "crates/api"
colette-backup.path = "crates/backup"
colette-config.path = "crates/config"
colette-core.path = "crates/core"
colette-feed.path = "crates/feed"
colette-http.path = "crates/http"
colette-meta.path = "crates/meta"
colette-migration.path = "crates/migration"
colette-netscape.path = "crates/netscape"
colette-opml.path = "crates/opml"
colette-plugins.path = "crates/plugins"
colette-queue = { path = "crates/queue", default-features = false }
colette-repository = { path = "crates/repository", default-features = false }
colette-scraper.path = "crates/scraper"
colette-session = { path = "crates/session", default-features = false }
colette-task.path = "crates/task"
colette-util.path = "crates/util"
colette-worker.path = "crates/worker"
console_error_panic_hook = { version = "0.1.7", default-features = false }
deadpool-postgres = { version = "0.14.1", default-features = false, features = [
  "rt_tokio_1",
] }
deadpool-sqlite = { version = "0.9.0", default-features = false, features = [
  "rt_tokio_1",
] }
email_address = { version = "0.2.9", default-features = false, features = [
  "serde_support",
] }
futures = { version = "0.3.31", default-features = false }
html5gum = { version = "0.7.0", default-features = false }
http = { version = "1.2.0", default-features = false, features = ["std"] }
quick-xml = { version = "0.37.2", default-features = false }
refinery-core = { git = "https://github.com/rust-db/refinery.git", default-features = false }
reqwest = { version = "0.12.12", default-features = false, features = [
  "rustls-tls",
] }
rust-embed = { version = "8.5.0", default-features = false, features = [
  "interpolate-folder-path",
] }
scraper = { version = "0.22.0", default-features = false }
sea-query = { version = "0.32.1", default-features = false, features = [
  "derive",
  "with-chrono",
  "with-json",
  "with-uuid",
] }
sea-query-postgres = { version = "0.5.0", default-features = false, features = [
  "with-chrono",
  "with-json",
  "with-uuid",
] }
serde = { version = "1.0.217", default-features = false }
serde_json = { version = "1.0.135", default-features = false }
thiserror = { version = "2.0.11", default-features = false }
tokio = { version = "1.43.0", default-features = false, features = ["macros"] }
tower = { version = "0.5.2", default-features = false, features = [
  "limit",
  "tracing",
] }
tower-http = { version = "0.6.2", default-features = false, features = [
  "cors",
  "fs",
  "trace",
] }
tower-sessions = { version = "0.14.0", default-features = false, features = [
  "axum-core",
] }
tracing = { version = "0.1.41", default-features = false }
tracing-subscriber = { version = "0.3.19", default-features = false, features = [
  "ansi",
  "env-filter",
  "tracing-log",
] }
url = { version = "2.5.4", default-features = false, features = ["serde"] }
uuid = { version = "1.11.1", default-features = false, features = [
  "serde",
  "v4",
] }
worker = { version = "0.5.0", default-features = false }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
