[workspace]

members = ["crates/core", "crates/postgres"]

[workspace.dependencies]
colette-core.path = "crates/core"
serde = { version = "1.0.203", features = ["derive"] }
time = { version = "0.3.36", features = ["serde"] }
