[workspace]
members = [
  "crates/api",
  "crates/core",
  "crates/database",
  "crates/password",
  "crates/postgres",
  "crates/scraper",
  "crates/sqlite",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
bytes = "1.6.0"
chrono = { version = "0.4.38", features = ["serde"] }
colette-core.path = "crates/core"
colette-database.path = "crates/database"
colette-password.path = "crates/password"
colette-postgres.path = "crates/postgres"
colette-scraper.path = "crates/scraper"
colette-sqlite.path = "crates/sqlite"
http = "1.1.0"
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.61"
url = "2.5.2"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = true
