[workspace]
members = [
  "crates/api",
  "crates/backup",
  "crates/config",
  "crates/core",
  "crates/password",
  "crates/plugins",
  "crates/postgres",
  "crates/scraper",
  "crates/server",
  "crates/tasks",
]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0.86", default-features = false, features = ["std"] }
async-trait = { version = "0.1.81", default-features = false }
chrono = { version = "0.4.38", default-features = false }
colette-api.path = "crates/api"
colette-backup.path = "crates/backup"
colette-config.path = "crates/config"
colette-core.path = "crates/core"
colette-password.path = "crates/password"
colette-plugins.path = "crates/plugins"
colette-postgres.path = "crates/postgres"
colette-scraper.path = "crates/scraper"
colette-tasks.path = "crates/tasks"
futures = { version = "0.3.30", default-features = false }
http = { version = "1.1.0", default-features = false, features = ["std"] }
lazy-regex = { version = "3.2.0", default-features = false, features = [
  "std",
  "perf",
] }
quick-xml = { version = "0.36.1", features = ["serialize"] }
serde = { version = "1.0.204", default-features = false }
thiserror = { version = "1.0.63", default-features = false }
tokio = { version = "1.39.2", default-features = false, features = [
  "macros",
  "rt-multi-thread",
] }
url = { version = "2.5.2", default-features = false }
uuid = { version = "1.10.0", default-features = false }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = true
