[workspace]
members = [
  "apps/server",
  "apps/desktop/src-tauri",

  "crates/api",
  "crates/backup",
  "crates/config",
  "crates/core",
  "crates/feed",
  "crates/meta",
  "crates/netscape",
  "crates/opml",
  "crates/plugins",
  "crates/postgres",
  "crates/scraper",
  "crates/session",
  "crates/sql",
  "crates/sqlite",
  "crates/task",
  "crates/util",
]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1", default-features = false, features = ["std"] }
async-trait = { version = "0.1", default-features = false }
axum = { version = "0.7", default-features = false, features = [
  "http1",
  "json",
  "query",
  "macros",
  "tokio",
] }
bytes = { version = "1", default-features = false }
chrono = { version = "0.4", default-features = false, features = [
  "clock",
  "serde",
  "std",
] }
colette-api.path = "crates/api"
colette-backup.path = "crates/backup"
colette-config.path = "crates/config"
colette-core.path = "crates/core"
colette-feed.path = "crates/feed"
colette-meta.path = "crates/meta"
colette-migration.path = "crates/migration"
colette-netscape.path = "crates/netscape"
colette-opml.path = "crates/opml"
colette-postgres.path = "crates/postgres"
colette-plugins.path = "crates/plugins"
colette-scraper.path = "crates/scraper"
colette-session.path = "crates/session"
colette-sql.path = "crates/sql"
colette-sqlite.path = "crates/sqlite"
colette-task.path = "crates/task"
colette-util.path = "crates/util"
email_address = { version = "0.2", default-features = false, features = [
  "serde_support",
] }
futures = { version = "0.3", default-features = false }
html5gum = { version = "0.5", default-features = false }
http = { version = "1", default-features = false, features = ["std"] }
quick-xml = { version = "0.36", default-features = false }
scraper = { version = "0.20", default-features = false }
sea-query = { version = "0.32", default-features = false, features = [
  "derive",
  "with-chrono",
  "with-json",
  "with-uuid",
] }
sea-query-binder = { version = "0.7", features = [
  "with-chrono",
  "with-json",
  "with-uuid",
] }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
sqlx = { version = "0.8", default-features = false, features = [
  "macros",
  "migrate",
  "runtime-tokio",
] }
thiserror = { version = "1", default-features = false }
tokio = { version = "1", default-features = false, features = [
  "macros",
  "rt-multi-thread",
] }
tower = { version = "0.5", default-features = false, features = [
  "limit",
  "tracing",
] }
tower-sessions = { version = "0.13", default-features = false, features = [
  "axum-core",
] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "ansi",
  "env-filter",
  "tracing-log",
] }
tower-sessions-core = { version = "0.13", default-features = false, features = [
  "deletion-task",
] }
tracing = { version = "0.1", default-features = false }
url = { version = "2", default-features = false, features = ["serde"] }
uuid = { version = "1", default-features = false, features = ["serde", "v4"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
