FROM node:22-alpine AS css-builder
WORKDIR /app
RUN npm i -D tailwindcss tailwindcss-animate
COPY ./crates/ui .
RUN npx tailwindcss -i input.css -o output.css

FROM rust:1.80-bullseye as base
WORKDIR /app
RUN wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-aarch64-unknown-linux-musl.tgz
RUN tar -xvf cargo-binstall-aarch64-unknown-linux-musl.tgz
RUN cp cargo-binstall /usr/local/cargo/bin
RUN rustup default nightly
RUN rustup target add wasm32-unknown-unknown
RUN cargo binstall -y cargo-chef cargo-leptos

FROM base as planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM base as builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
COPY --from=css-builder /app/output.css ./crates/ui/style/output.css
RUN cargo leptos build --release -vv

FROM debian:bookworm-slim as runtime
WORKDIR /app
COPY --from=builder /app/target/release/colette-ui .
COPY --from=builder /app/target/site ./site
ENV LEPTOS_SITE_ADDR="0.0.0.0:3000"
ENV LEPTOS_SITE_ROOT="site"
EXPOSE 3000
CMD ["colette-ui"]