services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"