services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    ports:
      - 8083:8080
    restart: unless-stopped
    volumes:
      - ./data/keycloak:/opt/keycloak/data/h2
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command:
      - start-dev
  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z
    ports:
      - 9000:9000
      - 9001:9001
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
  mc:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb -p local/colette;
      /usr/bin/mc anonymous set download local/colette/thumbnails;
      "
