config.default_to_workspace = false

[tasks.build-docker]
command = "docker"
args = ["build", "--platform", "linux/amd64", "-t", "colette-server", "."]

[tasks.build-docker-arm64]
command = "docker"
args = [
  "build",
  "--build-arg=TARGET=aarch64-unknown-linux-musl",
  "-t",
  "colette-server",
  ".",
]

[tasks.format-sql]
install_crate = "sqruff"
command = "sqruff"
args = ["fix", "schema", "apps/server/migrations"]
