config.default_to_workspace = false
env_files = [".env"]

[tasks.dev]
command = "cargo"
args = ["run"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.migrate]
command = "atlas"
args = [
  "migrate",
  "diff",
  "${@}",
  "--dir",
  "file://migrations",
  "--to",
  "file://schema.sql",
  "--dev-url",
  "sqlite://dev?mode=memory",
]

[tasks.build-docker]
command = "docker"
args = ["build", "--platform", "linux/amd64", "-t", "colette-server", "."]

[tasks.build-docker-arm64]
command = "docker"
args = [
  "build",
  "--build-arg=TARGET=aarch64-unknown-linux-musl",
  "-t",
  "colette-server",
  ".",
]
