env_files = [
  { path = ".env" },
  { path = ".env.production" },
  { path = ".env.sqlite", profile = "sqlite" },
]

config.default_to_workspace = false

[tasks.dev]
command = "cargo"
args = ["run", "-p", "colette-server"]

[tasks.run]
command = "cargo"
args = ["run", "--release", "-p", "colette-server"]
env_files = [".env.production"]

[tasks.build]
command = "cargo"
args = ["build", "--release", "-p", "colette-server"]

[tasks.prepare-pg]
cwd = "./crates/postgres"
command = "cargo"
args = ["sqlx", "prepare"]
env_files = [".env"]

[tasks.reset-pg]
cwd = "./crates/postgres"
command = "sqlx"
args = ["database", "reset"]
env_files = [".env"]

[tasks.prepare-sqlite]
cwd = "./crates/sqlite"
command = "cargo"
args = ["sqlx", "prepare"]
env_files = [".env.sqlite"]

[tasks.reset-sqlite]
cwd = "./crates/sqlite"
command = "sqlx"
args = ["database", "reset"]
env_files = [".env.sqlite"]
