config.default_to_workspace = false
env_files = [".env"]

[tasks.dev]
command = "cargo"
args = ["run"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.migrate-db]
install_crate = "sqlx-cli"
command = "sqlx"
args = ["migrate", "run"]

[tasks.reset-db]
install_crate = "sqlx-cli"
command = "sqlx"
args = ["db", "reset"]

[tasks.generate-migrate]
command = "atlas"
args = [
  "migrate",
  "diff",
  "${@}",
  "--dir",
  "file://migrations",
  "--to",
  "file://schema.sql",
  "--dev-url",
  "sqlite://dev?mode=memory",
]

[tasks.generate-models]
install_crate = true
command = "sea-orm-cli"
args = ["generate", "entity", "-o", "./crates/model/src/entity"]

[tasks.build-docker]
command = "docker"
args = ["build", "--platform", "linux/amd64", "-t", "colette-server", "."]

[tasks.build-docker-arm64]
command = "docker"
args = [
  "build",
  "--build-arg=TARGET=aarch64-unknown-linux-musl",
  "-t",
  "colette-server",
  ".",
]
