env_files = [".env"]

config.default_to_workspace = false

[tasks.dev]
command = "cargo"
args = ["run", "-p", "colette-server"]

[tasks.tauri-dev]
command = "npm"
args = ["run", "tauri", "dev", "--workspace=@colette/desktop"]

[tasks.build]
command = "cargo"
args = ["build", "--release", "-p", "colette-server"]

[tasks.build-docker]
command = "docker"
args = ["build", "--platform", "linux/amd64", "-t", "colette-server", "."]

[tasks.build-docker-arm64]
command = "docker"
args = [
  "build",
  "--build-arg=TARGET=aarch64-unknown-linux-musl",
  "-t",
  "colette-server",
  ".",
]

[tasks.db-reset]
install_crate = "sea-orm-cli"
command = "sea-orm-cli"
args = ["migrate", "fresh", "-d", "./crates/migration"]

[tasks.db-generate]
install_crate = "sea-orm-cli"
command = "sea-orm-cli"
args = ["generate", "entity", "-o", "./crates/entity/src/generated"]

[tasks.bloat]
install_crate = "cargo-bloat"
command = "cargo"
args = ["bloat", "--release", "--crates", "-p", "colette-server"]
