env_files = [".env", ".env.sqlite"]

config.default_to_workspace = false

[tasks.dev]
command = "cargo"
args = ["run", "-p", "colette-api"]

[tasks.run]
command = "cargo"
args = ["run", "--release", "-p", "colette-api"]

[tasks.build]
command = "cargo"
args = ["build", "--release", "-p", "colette-api"]

[tasks.prepare-pg]
cwd = "./crates/postgres"
command = "cargo"
args = ["sqlx", "prepare"]

[tasks.reset-pg]
cwd = "./crates/postgres"
command = "sqlx"
args = ["database", "reset"]

[tasks.prepare-sqlite]
env_files = [".env.sqlite"]
cwd = "./crates/sqlite"
command = "cargo"
args = ["sqlx", "prepare"]

[tasks.reset-sqlite]
env_files = [".env.sqlite"]
cwd = "./crates/sqlite"
command = "sqlx"
args = ["database", "reset"]
