config.default_to_workspace = false
env_files = [".env"]

[tasks.dev-api]
command = "cargo"
args = ["run", "-p", "colette-api"]

[tasks.dev-worker]
command = "cargo"
args = ["run", "-p", "colette-worker"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
