env_files = [".env"]

config.default_to_workspace = false

[tasks.dev]
command = "cargo"
args = ["run", "-p", "colette-server"]

[tasks.run]
command = "cargo"
args = ["run", "--release", "-p", "colette-server"]

[tasks.build]
command = "cargo"
args = ["build", "--release", "-p", "colette-server"]

[tasks.reset]
command = "sqlx"
args = ["db", "reset"]

[tasks.prepare]
cwd = "./crates/postgres"
command = "cargo"
args = ["sqlx", "prepare"]
