env_files = [{ path = ".env" }, { path = ".env.sqlite", profile = "sqlite" }]

config.default_to_workspace = false

[tasks.dev]
command = "cargo"
args = ["run", "-p", "colette-server"]

[tasks.run]
command = "cargo"
args = ["run", "--release", "-p", "colette-server"]
env_files = [".env.production"]

[tasks.build]
command = "cargo"
args = ["build", "--release", "-p", "colette-server"]

[tasks.migrate]
command = "sea-orm-cli"
args = ["migrate", "fresh", "-d", "./crates/migrations"]

[tasks.generate]
command = "sea-orm-cli"
args = ["generate", "entity", "-o", "./crates/entities/src/generated"]
