env_files = [".env"]

config.default_to_workspace = false

[tasks.dev]
command = "cargo"
args = ["run", "-p", "colette-server"]

[tasks.run]
command = "cargo"
args = ["run", "--release", "-p", "colette-server"]

[tasks.watch-tw]
cwd = "./crates/ui"
command = "npx"
args = [
  "tailwindcss",
  "-i",
  "./input.css",
  "-o",
  "./style/output.css",
  "--watch",
]

[tasks.watch-ui]
install_crate = "cargo-leptos"
command = "cargo"
args = ["leptos", "watch"]

[tasks.build]
command = "cargo"
args = ["build", "--release", "-p", "colette-server"]

[tasks.build-tw]
cwd = "./crates/ui"
command = "npx"
args = ["tailwindcss", "-i", "./input.css", "-o", "./style/output.css"]

[tasks.build-ui]
dependencies = ["build-tw"]
install_crate = "cargo-leptos"
command = "cargo"
args = ["leptos", "build", "--release"]

[tasks.db-reset]
install_crate = "sqlx-cli"
command = "sqlx"
args = ["db", "reset"]

[tasks.db-prepare]
install_crate = "sqlx-cli"
cwd = "./crates/postgres"
command = "cargo"
args = ["sqlx", "prepare"]

[tasks.bloat]
install_crate = "cargo-bloat"
command = "cargo"
args = ["bloat", "--release", "--crates"]
