config.default_to_workspace = false
env_files = [".env"]

[tasks.dev]
command = "cargo"
args = ["run"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.migrate-db]
install_crate = "refinery_cli"
command = "refinery"
args = ["migrate", "-e", "DATABASE_URL"]
