[package]
name = "colette-cloudflare"
version = "0.1.0"
edition = "2021"

[package.metadata.release]
release = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
axum.workspace = true
chrono.workspace = true
console_error_panic_hook = { version = "0.1", default-features = false }
sea-query = { workspace = true, features = ["backend-sqlite"] }
serde.workspace = true
tower.workspace = true
worker = { version = "0.4", default-features = false, features = [
  "axum",
  "d1",
  "http",
] }
