name = "colette"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-16"
vars = { API_PREFIX = "/api/v1" }

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "colette"
database_id = "5ad3b676-f857-4fd2-a23c-7920104e6470"

[[kv_namespaces]]
binding = "KV"
id = "bb3ea6e79a3f46f9a18f4ee2f0f3930d"

[observability]
enabled = true

[[queues.consumers]]
queue = "colette"

[[queues.producers]]
binding = "QUEUE"
queue = "colette"
