[server]
port = 8000
base_url = "http://localhost:8000"

[cors]
enabled = false
origin_urls = []

[s3]
bucket_name = "colette"
path_style_enabled = true

[oidc]
enabled = false
scopes = ["email", "profile"]
sign_in_text = "Sign in with OIDC"
