[package]
name = "colette-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
futures.workspace = true
rust-s3 = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[features]
fs = ['dep:tokio']
s3 = ["dep:rust-s3"]
