[package]
name = "colette-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
futures.workspace = true
tokio = { workspace = true, optional = true }

[features]
local = ['dep:tokio']
