[package]
name = "colette-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
colette-core.workspace = true
colette-netscape.workspace = true
colette-opml.workspace = true
colette-sql.workspace = true
futures.workspace = true
sea-query = { workspace = true, features = ["backend-sqlite"] }
sea-query-binder = { workspace = true, features = ["sqlx-sqlite"] }
serde.workspace = true
sqlx.workspace = true
