[package]
name = "colette-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
chrono.workspace = true
colette-core.workspace = true
colette-database.workspace = true
sqlx = { version = "0.7.4", features = ["chrono", "sqlite", "runtime-tokio"] }
