[package]
name = "colette-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
colette-core.workspace = true
colette-database.workspace = true
futures.workspace = true
sqlx = { workspace = true, features = ["sqlite"] }
uuid = { workspace = true, features = ["v4"] }
