[package]
name = "colette-meta"
version = "0.1.0"
edition = "2021"

[dependencies]
html5gum.workspace = true
ordered-float = { version = "4.6.0", default-features = false }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
