[package]
name = "colette-meta"
version = "0.1.0"
edition = "2021"

[dependencies]
html5ever = { version = "0.28", default-features = false }
ordered-float = { version = "4", default-features = false }
serde.workspace = true
serde_json = { version = "1", default-features = false }
