[package]
name = "colette-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
axum = { workspace = true, features = ["tokio"] }
axum-embed = { version = "0.1", default-features = false }
colette-api.workspace = true
colette-backup.workspace = true
colette-config.workspace = true
colette-core.workspace = true
colette-plugins.workspace = true
colette-postgres.workspace = true
colette-scraper.workspace = true
colette-task.workspace = true
colette-util.workspace = true
colette-worker.workspace = true
reqwest.workspace = true
rust-embed = { version = "8", default-features = false, features = [
  "interpolate-folder-path",
] }
sqlx.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http = { version = "0.6", default-features = false, features = [
  "cors",
  "fs",
  "trace",
] }
tower-sessions.workspace = true
tower-sessions-core.workspace = true
tracing-subscriber.workspace = true
