[package]
name = "colette-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
axum = { workspace = true, features = ["tokio"] }
axum-embed.workspace = true
colette-api.workspace = true
colette-backup.workspace = true
colette-config.workspace = true
colette-core.workspace = true
colette-http.workspace = true
colette-plugins.workspace = true
colette-queue = { workspace = true, features = ["in-memory"] }
colette-repository = { workspace = true, features = ["postgres"] }
colette-scraper.workspace = true
colette-session = { workspace = true, features = ["postgres"] }
colette-task.workspace = true
colette-util.workspace = true
colette-worker.workspace = true
rust-embed.workspace = true
sqlx = { workspace = true, features = ["postgres"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tower.workspace = true
tower-http.workspace = true
tower-sessions.workspace = true
tracing-subscriber.workspace = true
