[package]
name = "colette-server"
version = "0.1.0"
edition = "2021"

[dependencies]
apalis.workspace = true
apalis-cron = { version = "0.6.4", default-features = false }
apalis-redis = { version = "0.6.4", default-features = false, features = [
  "tokio-comp",
] }
async-trait.workspace = true
axum = { workspace = true, features = ["tokio"] }
axum-embed.workspace = true
colette-api.workspace = true
colette-archiver.workspace = true
colette-backup.workspace = true
colette-core.workspace = true
colette-plugins.workspace = true
colette-repository.workspace = true
colette-scraper.workspace = true
colette-task.workspace = true
colette-util.workspace = true
envy = { version = "0.4.2", default-features = false }
redis.workspace = true
reqwest.workspace = true
rust-embed.workspace = true
rust-s3.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["postgres"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tower.workspace = true
tower-http.workspace = true
tower-sessions.workspace = true
tower-sessions-core = { version = "0.14.0", default-features = false }
tracing-subscriber.workspace = true
