[package]
name = "colette-server"
version = "0.1.0"
edition = "2021"

[dependencies]
apalis.workspace = true
apalis-cron = { version = "=0.6.0-rc.7", default-features = false }
async-trait.workspace = true
axum.workspace = true
axum-embed = { version = "0.1", default-features = false }
colette-api.workspace = true
colette-backup.workspace = true
colette-config.workspace = true
colette-core.workspace = true
colette-plugins.workspace = true
colette-postgres = { workspace = true, optional = true }
colette-scraper.workspace = true
colette-session.workspace = true
colette-sqlite = { workspace = true, optional = true }
colette-task.workspace = true
colette-util.workspace = true
deadpool-postgres = { workspace = true, optional = true }
deadpool-sqlite = { workspace = true, optional = true }
rust-embed = { version = "8", default-features = false, features = [
  "interpolate-folder-path",
] }
tokio.workspace = true
tokio-postgres = { workspace = true, optional = true }
tower-sessions-core.workspace = true
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "ansi",
  "env-filter",
  "tracing-log",
] }

[features]
default = ["postgres", "sqlite"]
postgres = [
  "dep:colette-postgres",
  "dep:deadpool-postgres",
  "dep:tokio-postgres",
  "colette-session/postgres",
]
sqlite = ["dep:colette-sqlite", "dep:deadpool-sqlite", "colette-session/sqlite"]
