[package]
name = "colette-server"
version = "0.1.0"
edition = "2024"

[dependencies]
apalis = { version = "0.6.4", default-features = false, features = [
  "limit",
  "tracing",
] }
apalis-cron = { version = "0.6.4", default-features = false }
apalis-redis.workspace = true
async-trait.workspace = true
axum.workspace = true
axum-embed.workspace = true
colette-api.workspace = true
colette-archiver.workspace = true
colette-core.workspace = true
colette-http.workspace = true
colette-plugins.workspace = true
colette-repository.workspace = true
colette-scraper.workspace = true
colette-util.workspace = true
envy = { version = "0.4.2", default-features = false }
futures.workspace = true
hyper-rustls.workspace = true
hyper-util.workspace = true
redis.workspace = true
rust-embed.workspace = true
rust-s3.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
tower-sessions.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
