env_files = [".env"]

[tasks.dev]
command = "cargo"
args = ["run"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.migrate]
command = "atlas"
args = [
  "migrate",
  "diff",
  "${@}",
  "--dir",
  "file://migrations",
  "--to",
  "file://../../schema/postgresql.sql",
  "--dev-url",
  "docker://postgres/17/dev",
]
