[package]
name = "colette-desktop"
version = "0.1.0"
edition = "2021"

[lib]
name = "colette_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", default-features = false, features = [
  "config-json",
] }

[dependencies]
colette-api.workspace = true
colette-backup.workspace = true
colette-core.workspace = true
colette-migration = { workspace = true, features = ["sqlite"] }
colette-plugins.workspace = true
colette-repository.workspace = true
colette-util.workspace = true
email_address.workspace = true
sea-orm = { workspace = true, features = ["sqlx-sqlite"] }
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2.0.0-rc", default-features = false, features = [
  "wry",
  "compression",
] }
tauri-plugin-shell = { version = "2.0.0-rc", default-features = false }
uuid.workspace = true
