[package]
name = "colette-desktop"
version = "0.1.0"
edition = "2021"

[lib]
name = "colette_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", default-features = false, features = [
  "config-json",
] }

[dependencies]
colette-api.workspace = true
colette-backup.workspace = true
colette-core.workspace = true
colette-plugins.workspace = true
colette-queue = { workspace = true, features = ["in-memory"] }
colette-scraper.workspace = true
colette-sql = { workspace = true, features = ["sqlite"] }
colette-task.workspace = true
colette-util.workspace = true
colette-worker.workspace = true
email_address.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["sqlite"] }
tauri = { version = "2", default-features = false, features = [
  "wry",
  "compression",
] }
tauri-plugin-shell = { version = "2", default-features = false }
tokio.workspace = true
tower.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
