[package]
name = "colette-desktop"
version = "0.1.0"
edition = "2021"

[lib]
name = "colette_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", default-features = false, features = [
  "config-json",
] }

[dependencies]
tauri = { version = "2.0.0-rc", default-features = false, features = [
  "wry",
  "compression",
] }
tauri-plugin-shell = { version = "2.0.0-rc", default-features = false }
serde.workspace = true
serde_json.workspace = true
