[package]
name = "colette-smtp"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
lettre = { version = "0.11.18", default-features = false, features = [
  "builder",
  "hostname",
  "pool",
  "smtp-transport",
  "tokio1-rustls-tls",
] }
thiserror.workspace = true
