CREATE TABLE profile_feeds (
  id TEXT NOT NULL PRIMARY KEY,
  title TEXT,
  pinned INTEGER NOT NULL DEFAULT 0,
  profile_id TEXT NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  feed_id INTEGER NOT NULL REFERENCES feeds (id) ON DELETE RESTRICT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (profile_id, feed_id)
);

CREATE TABLE profile_feed_entries (
  id TEXT NOT NULL PRIMARY KEY,
  has_read INTEGER NOT NULL DEFAULT 0,
  profile_feed_id TEXT NOT NULL REFERENCES profile_feeds (id) ON DELETE CASCADE,
  feed_entry_id INTEGER NOT NULL REFERENCES feed_entries (id) ON DELETE RESTRICT,
  profile_id TEXT NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (profile_feed_id, feed_entry_id)
);