[package]
name = "colette-repository"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
chrono.workspace = true
colette-core.workspace = true
colette-netscape.workspace = true
colette-opml.workspace = true
futures.workspace = true
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true
