[package]
name = "colette-repository"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
colette-core.workspace = true
colette-entity.workspace = true
colette-netscape.workspace = true
colette-opml.workspace = true
colette-util.workspace = true
futures.workspace = true
indexmap = { version = "2", default-features = false }
sea-orm.workspace = true
