[package]
name = "colette-repository"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
chrono.workspace = true
colette-core.workspace = true
colette-netscape.workspace = true
colette-opml.workspace = true
futures.workspace = true
sea-query = { version = "0.32.1", default-features = false, features = [
  "backend-postgres",
  "derive",
  "with-chrono",
  "with-json",
  "with-uuid",
] }
sea-query-binder = { version = "0.7.0", default-features = false, features = [
  "sqlx-postgres",
  "with-chrono",
  "with-json",
  "with-uuid",
] }
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true
