[package]
name = "colette-repository"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
colette-core.workspace = true
colette-netscape.workspace = true
colette-opml.workspace = true
colette-postgres = { workspace = true, optional = true }
futures.workspace = true
sqlx.workspace = true

[features]
default = ["postgres"]
postgres = ["colette-postgres"]
