[package]
name = "colette-repository"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
chrono.workspace = true
colette-core.workspace = true
colette-netscape.workspace = true
colette-opml.workspace = true
futures.workspace = true
sea-query.workspace = true
sea-query-binder = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["postgres"] }
thiserror.workspace = true
uuid.workspace = true

[features]
default = ["postgres"]
postgres = ["sea-query/backend-postgres", "dep:sea-query-binder"]
