[package]
name = "colette-queue"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
thiserror.workspace = true
tokio = { workspace = true, optional = true }
uuid.workspace = true

[features]
default = ["local"]
local = ["dep:tokio"]
