[package]
name = "colette-password"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
colette-core.workspace = true
password-auth = { version = "1.0.0", default-features = false, features = [
  "argon2",
] }
