[package]
name = "sqlite2"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.30.0", features = ["bundled", "chrono", "uuid"] }
sea-query = { version = "0.31.0-rc.9", features = ["with-chrono", "with-uuid"] }
