//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "feeds")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub link: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::feed_entries::Entity")]
    FeedEntries,
    #[sea_orm(has_many = "super::profile_feeds::Entity")]
    ProfileFeeds,
}

impl Related<super::feed_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeedEntries.def()
    }
}

impl Related<super::profile_feeds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProfileFeeds.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
