//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "feed")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub link: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::feed_entry::Entity")]
    FeedEntry,
    #[sea_orm(has_many = "super::profile_feed::Entity")]
    ProfileFeed,
}

impl Related<super::feed_entry::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeedEntry.def()
    }
}

impl Related<super::profile_feed::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProfileFeed.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
