//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.7

pub mod prelude;

pub mod bookmark_tags;
pub mod bookmarks;
pub mod collections;
pub mod entries;
pub mod feed_entries;
pub mod feeds;
pub mod profile_feed_entries;
pub mod profile_feed_tags;
pub mod profile_feeds;
pub mod profiles;
pub mod tags;
pub mod users;
