//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.7

pub use super::{
    bookmark::Entity as Bookmark, bookmark_tag::Entity as BookmarkTag,
    collection::Entity as Collection, entry::Entity as Entry, feed::Entity as Feed,
    feed_entry::Entity as FeedEntry, profile::Entity as Profile,
    profile_feed::Entity as ProfileFeed, profile_feed_entry::Entity as ProfileFeedEntry,
    profile_feed_tag::Entity as ProfileFeedTag, tag::Entity as Tag, user::Entity as User,
};
