//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.7

pub use super::{
    bookmark_tags::Entity as BookmarkTags, bookmarks::Entity as Bookmarks,
    collections::Entity as Collections, entries::Entity as Entries,
    feed_entries::Entity as FeedEntries, feeds::Entity as Feeds,
    profile_feed_entries::Entity as ProfileFeedEntries,
    profile_feed_tags::Entity as ProfileFeedTags, profile_feeds::Entity as ProfileFeeds,
    profiles::Entity as Profiles, tags::Entity as Tags, users::Entity as Users,
};
