//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "profile_feed_entries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub has_read: bool,
    pub profile_feed_id: Uuid,
    pub feed_entry_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::feed_entries::Entity",
        from = "Column::FeedEntryId",
        to = "super::feed_entries::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    FeedEntries,
    #[sea_orm(
        belongs_to = "super::profile_feeds::Entity",
        from = "Column::ProfileFeedId",
        to = "super::profile_feeds::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ProfileFeeds,
}

impl Related<super::feed_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeedEntries.def()
    }
}

impl Related<super::profile_feeds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProfileFeeds.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
