//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "profile_feed_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub profile_feed_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::profile_feeds::Entity",
        from = "Column::ProfileFeedId",
        to = "super::profile_feeds::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ProfileFeeds,
    #[sea_orm(
        belongs_to = "super::tags::Entity",
        from = "Column::TagId",
        to = "super::tags::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tags,
}

impl Related<super::profile_feeds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProfileFeeds.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
