//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub profile_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bookmark_tags::Entity")]
    BookmarkTags,
    #[sea_orm(has_many = "super::profile_feed_tags::Entity")]
    ProfileFeedTags,
    #[sea_orm(
        belongs_to = "super::profiles::Entity",
        from = "Column::ProfileId",
        to = "super::profiles::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Profiles,
}

impl Related<super::bookmark_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookmarkTags.def()
    }
}

impl Related<super::profile_feed_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProfileFeedTags.def()
    }
}

impl Related<super::profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profiles.def()
    }
}

impl Related<super::bookmarks::Entity> for Entity {
    fn to() -> RelationDef {
        super::bookmark_tags::Relation::Bookmarks.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::bookmark_tags::Relation::Tags.def().rev())
    }
}

impl Related<super::profile_feeds::Entity> for Entity {
    fn to() -> RelationDef {
        super::profile_feed_tags::Relation::ProfileFeeds.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::profile_feed_tags::Relation::Tags.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
