[package]
name = "colette-s3"
version = "0.1.0"
edition = "2024"

[dependencies]
futures.workspace = true
rust-s3 = { version = "=0.36.0-beta.2", default-features = false, features = [
  "fail-on-err",
  "tokio-rustls-tls",
] }
thiserror.workspace = true
