[package]
name = "colette-oidc"
version = "0.1.0"
edition = "2024"

[dependencies]
oauth2 = { version = "5.0.0", default-features = false, features = ["reqwest"] }
openidconnect = { version = "4.0.1", default-features = false }
reqwest.workspace = true
thiserror.workspace = true
url.workspace = true
