[package]
name = "colette-jwt"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
jsonwebtoken = { version = "9.3.1", default-features = false }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
