[package]
name = "colette-archiver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
reqwest.workspace = true
rust-s3.workspace = true
thiserror.workspace = true
url.workspace = true
