[package]
name = "colette-archiver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
colette-http.workspace = true
image = { version = "0.25.5", default-features = false }
rust-s3.workspace = true
thiserror.workspace = true
url.workspace = true
