/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as PrivateImport } from './routes/_private'
import { Route as PrivateIndexImport } from './routes/_private/index'
import { Route as PrivateFeedsImport } from './routes/_private/feeds'
import { Route as PrivateCollectionsImport } from './routes/_private/collections'
import { Route as PrivateFeedsIndexImport } from './routes/_private/feeds/index'
import { Route as PrivateFeedsArchivedImport } from './routes/_private/feeds/archived'
import { Route as PrivateFeedsIdImport } from './routes/_private/feeds/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const PrivateIndexRoute = PrivateIndexImport.update({
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateFeedsRoute = PrivateFeedsImport.update({
  path: '/feeds',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateCollectionsRoute = PrivateCollectionsImport.update({
  path: '/collections',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateFeedsIndexRoute = PrivateFeedsIndexImport.update({
  path: '/',
  getParentRoute: () => PrivateFeedsRoute,
} as any)

const PrivateFeedsArchivedRoute = PrivateFeedsArchivedImport.update({
  path: '/archived',
  getParentRoute: () => PrivateFeedsRoute,
} as any)

const PrivateFeedsIdRoute = PrivateFeedsIdImport.update({
  path: '/$id',
  getParentRoute: () => PrivateFeedsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_private/collections': {
      id: '/_private/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof PrivateCollectionsImport
      parentRoute: typeof PrivateImport
    }
    '/_private/feeds': {
      id: '/_private/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof PrivateFeedsImport
      parentRoute: typeof PrivateImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/feeds/$id': {
      id: '/_private/feeds/$id'
      path: '/$id'
      fullPath: '/feeds/$id'
      preLoaderRoute: typeof PrivateFeedsIdImport
      parentRoute: typeof PrivateFeedsImport
    }
    '/_private/feeds/archived': {
      id: '/_private/feeds/archived'
      path: '/archived'
      fullPath: '/feeds/archived'
      preLoaderRoute: typeof PrivateFeedsArchivedImport
      parentRoute: typeof PrivateFeedsImport
    }
    '/_private/feeds/': {
      id: '/_private/feeds/'
      path: '/'
      fullPath: '/feeds/'
      preLoaderRoute: typeof PrivateFeedsIndexImport
      parentRoute: typeof PrivateFeedsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  PrivateRoute: PrivateRoute.addChildren({
    PrivateCollectionsRoute,
    PrivateFeedsRoute: PrivateFeedsRoute.addChildren({
      PrivateFeedsIdRoute,
      PrivateFeedsArchivedRoute,
      PrivateFeedsIndexRoute,
    }),
    PrivateIndexRoute,
  }),
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_private",
        "/login"
      ]
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/collections",
        "/_private/feeds",
        "/_private/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_private/collections": {
      "filePath": "_private/collections.tsx",
      "parent": "/_private"
    },
    "/_private/feeds": {
      "filePath": "_private/feeds.tsx",
      "parent": "/_private",
      "children": [
        "/_private/feeds/$id",
        "/_private/feeds/archived",
        "/_private/feeds/"
      ]
    },
    "/_private/": {
      "filePath": "_private/index.tsx",
      "parent": "/_private"
    },
    "/_private/feeds/$id": {
      "filePath": "_private/feeds/$id.tsx",
      "parent": "/_private/feeds"
    },
    "/_private/feeds/archived": {
      "filePath": "_private/feeds/archived.tsx",
      "parent": "/_private/feeds"
    },
    "/_private/feeds/": {
      "filePath": "_private/feeds/index.tsx",
      "parent": "/_private/feeds"
    }
  }
}
ROUTE_MANIFEST_END */
