[package]
name = "colette-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
colette-core.workspace = true
http.workspace = true
itertools = "0.13.0"
libxml = "0.3.3"
reqwest = "0.12.5"
url.workspace = true
