[package]
name = "colette-api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
axum.workspace = true
axum-extra = { version = "0.9", default-features = false, features = ["query"] }
bytes.workspace = true
chrono.workspace = true
colette-backup.workspace = true
colette-config.workspace = true
colette-core.workspace = true
email_address.workspace = true
http.workspace = true
serde.workspace = true
serde_with = { version = "3", default-features = false }
thiserror.workspace = true
tower-http = { version = "0.5", default-features = false, features = [
  "cors",
  "fs",
] }
tower-sessions.workspace = true
url.workspace = true
utoipa = { version = "=5.0.0-beta.0", default-features = false, features = [
  "chrono",
  "macros",
  "preserve_order",
  "preserve_path_order",
  "url",
  "uuid",
] }
utoipa-axum = { version = "=0.1.0-beta.2", default-features = false }
utoipa-scalar = { version = "=0.2.0-beta.0", default-features = false, features = [
  "axum",
] }
uuid.workspace = true
