[package]
name = "colette-api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
axum.workspace = true
axum-extra = { version = "0.9", default-features = false, features = ["query"] }
bytes.workspace = true
chrono.workspace = true
colette-backup.workspace = true
colette-config.workspace = true
colette-core.workspace = true
email_address = { version = "0.2", default-features = false, features = [
  "serde",
  "serde_support",
] }
http.workspace = true
serde.workspace = true
serde_with = { version = "3", default-features = false }
thiserror.workspace = true
tower-http.workspace = true
tower-sessions.workspace = true
utoipa = { version = "5.0.0-alpha.2", default-features = false, features = [
  "chrono",
  "preserve_order",
  "preserve_path_order",
  "url",
  "uuid",
] }
utoipa-scalar = { version = "0.2.0-alpha.0", default-features = false, features = [
  "axum",
] }
url.workspace = true
uuid.workspace = true
