[package]
name = "colette-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.5", features = ["macros"] }
bytes.workspace = true
chrono.workspace = true
colette-core.workspace = true
colette-password.workspace = true
colette-postgres.workspace = true
colette-scraper.workspace = true
colette-sqlite.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
tower-sessions = "0.12.2"
tower-sessions-sqlx-store = { version = "0.12.0", features = [
  "postgres",
  "sqlite",
] }
url.workspace = true
utoipa = { version = "5.0.0-alpha.0", features = [
  "chrono",
  "preserve_order",
  "preserve_path_order",
  "url",
] }
utoipa-scalar = { version = "0.2.0-alpha.0", features = ["axum"] }
