[package]
name = "colette-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
axum-extra.workspace = true
bytes.workspace = true
chrono.workspace = true
colette-core.workspace = true
colette-task.workspace = true
email_address.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with = { version = "3.12.0", default-features = false }
thiserror.workspace = true
tokio.workspace = true
tower-sessions.workspace = true
tracing.workspace = true
url.workspace = true
utoipa = { version = "5.3.1", default-features = false, features = [
  "chrono",
  "macros",
  "preserve_order",
  "preserve_path_order",
  "url",
  "uuid",
] }
utoipa-axum = { version = "0.2.0", default-features = false }
utoipa-scalar = { version = "0.3.0", default-features = false, features = [
  "axum",
] }
uuid.workspace = true
