[package]
name = "colette-api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
axum = { version = "0.7.5", default-features = false, features = [
  "http1",
  "macros",
  "multipart",
  "tokio",
] }
axum-embed = { version = "0.1.0", default-features = false }
axum-valid = { version = "0.19.0", default-features = false, features = [
  "422",
  "basic",
  "into_json",
  "validator",
] }
chrono = { workspace = true, features = ["serde"] }
colette-config.workspace = true
colette-core.workspace = true
rust-embed = { version = "8.5.0", default-features = false, features = [
  "interpolate-folder-path",
] }
serde.workspace = true
serde_json = { version = "1.0.121", default-features = false }
sqlx = { version = "0.8.0", default-features = false, features = ["migrate"] }
thiserror.workspace = true
tokio.workspace = true
tower-http = { version = "0.5.2", default-features = false, features = [
  "cors",
] }
tower-sessions = { version = "0.12.2", default-features = false, features = [
  "axum-core",
] }
tower-sessions-sqlx-store = { version = "0.13.0", default-features = false, features = [
  "postgres",
] }
utoipa = { version = "5.0.0-alpha.1", default-features = false, features = [
  "chrono",
  "preserve_order",
  "preserve_path_order",
  "uuid",
] }
utoipa-scalar = { version = "0.2.0-alpha.0", default-features = false, features = [
  "axum",
] }
url.workspace = true
uuid = { workspace = true, features = ["serde"] }
validator = { version = "0.18.1", default-features = false, features = [
  "derive",
] }
