[package]
name = "colette-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
anyhow.workspace = true
chrono.workspace = true
colette-feed.workspace = true
colette-meta.workspace = true
http.workspace = true
scraper.workspace = true
thiserror.workspace = true
ureq = { version = "2", default-features = false, features = [
  "http-crate",
  "tls",
] }
url.workspace = true
