[package]
name = "colette-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
colette-core.workspace = true
http.workspace = true
reqwest = "0.12.5"
skyscraper = "0.7.0-beta.1"
url.workspace = true
