[package]
name = "colette-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
colette-core.workspace = true
http.workspace = true
quick-xml = { version = "0.36.0", default-features = false, features = [
  "overlapped-lists",
  "serialize",
] }
scraper = { version = "0.19.1", default-features = false }
serde.workspace = true
ureq = { version = "2.10.0", default-features = false, features = [
  "http-crate",
  "tls",
] }
url.workspace = true
