[package]
name = "colette-migration"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
libsql.workspace = true
refinery-core = { version = "0.8.16", default-features = false }
serde.workspace = true
sqlx.workspace = true
time.workspace = true
