[package]
name = "colette-migration"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
refinery-core = { version = "0.8.16", default-features = false }
sqlx.workspace = true
time = { version = "0.3.39", default-features = false }
