[package]
name = "colette-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
colette-core.workspace = true
quick-xml.workspace = true
serde.workspace = true
url = { workspace = true, features = ["serde"] }
