[package]
name = "colette-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes.workspace = true
quick-xml.workspace = true
serde.workspace = true
thiserror.workspace = true
url.workspace = true
