[package]
name = "colette-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes.workspace = true
colette-netscape.workspace = true
colette-opml.workspace = true
dyn-clone.workspace = true
thiserror.workspace = true
