[package]
name = "colette-core"
version = "0.1.0"
edition = "2024"

[dependencies]
apalis-core.workspace = true
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
colette-feed.workspace = true
colette-http.workspace = true
colette-meta.workspace = true
colette-netscape.workspace = true
colette-opml.workspace = true
colette-util.workspace = true
futures.workspace = true
image = { version = "0.25.5", default-features = false }
object_store.workspace = true
reqwest.workspace = true
scraper.workspace = true
sea-orm.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true
