[package]
name = "colette-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
email_address = { version = "0.2", default-features = false, features = [
  "serde",
  "serde_support",
] }
futures.workspace = true
http.workspace = true
serde.workspace = true
thiserror.workspace = true
url.workspace = true
uuid.workspace = true
