[package]
name = "colette-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
colette-archiver.workspace = true
colette-backup.workspace = true
colette-netscape.workspace = true
colette-opml.workspace = true
colette-scraper.workspace = true
colette-util.workspace = true
email_address.workspace = true
futures.workspace = true
serde.workspace = true
thiserror.workspace = true
url.workspace = true
uuid.workspace = true
