[package]
name = "colette-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
chrono.workspace = true
http.workspace = true
serde.workspace = true
thiserror.workspace = true
