[package]
name = "colette-task"
version = "0.1.0"
edition = "2021"

[dependencies]
colette-core.workspace = true
colette-queue.workspace = true
futures.workspace = true
serde.workspace = true
tower.workspace = true
tracing.workspace = true
url.workspace = true
