[package]
name = "colette-task"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
apalis.workspace = true
apalis-core.workspace = true
async-trait.workspace = true
chrono.workspace = true
colette-core.workspace = true
colette-scraper.workspace = true
cron = { version = "0.12", default-features = false }
futures.workspace = true
serde.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

[features]
default = []
postgres = ["apalis/postgres"]
sqlite = ["apalis/sqlite"]
