//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

pub use super::{
    accounts::Entity as Accounts, api_keys::Entity as ApiKeys,
    bookmark_tags::Entity as BookmarkTags, bookmarks::Entity as Bookmarks,
    collections::Entity as Collections, feed_entries::Entity as FeedEntries,
    feeds::Entity as Feeds, sessions::Entity as Sessions, streams::Entity as Streams,
    tags::Entity as Tags, user_feed_entries::Entity as UserFeedEntries,
    user_feed_tags::Entity as UserFeedTags, user_feeds::Entity as UserFeeds,
    users::Entity as Users,
};
