//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_feed_entries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub has_read: i32,
    #[sea_orm(column_type = "Text")]
    pub user_feed_id: String,
    pub feed_entry_id: i32,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::feed_entries::Entity",
        from = "Column::FeedEntryId",
        to = "super::feed_entries::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    FeedEntries,
    #[sea_orm(
        belongs_to = "super::user_feeds::Entity",
        from = "Column::UserFeedId",
        to = "super::user_feeds::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserFeeds,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::feed_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeedEntries.def()
    }
}

impl Related<super::user_feeds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFeeds.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
