[package]
name = "colette-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
colette-core.workspace = true
colette-database.workspace = true
futures.workspace = true
sqlx = { version = "0.7.4", default-features = false, features = [
  "chrono",
  "postgres",
  "runtime-tokio",
  "uuid",
] }
