[package]
name = "colette-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
colette-core.workspace = true
sqlx = { version = "0.7.4", features = ["postgres", "runtime-tokio", "time"] }
thiserror.workspace = true
time.workspace = true
