[package]
name = "colette-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
colette-core.workspace = true
futures.workspace = true
sea-query = { workspace = true, features = [
  "backend-postgres",
  "postgres-array",
] }
sea-query-binder = { workspace = true, features = [
  "postgres-array",
  "sqlx-postgres",
] }
serde.workspace = true
sqlx.workspace = true
