[package]
name = "colette-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
colette-core.workspace = true
nanoid = "0.4.0"
sqlx = { version = "0.7.4", features = ["postgres", "runtime-tokio", "time"] }
time.workspace = true
