[package]
name = "colette-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
colette-core.workspace = true
colette-netscape.workspace = true
colette-opml.workspace = true
colette-sql.workspace = true
deadpool-postgres.workspace = true
futures.workspace = true
sea-query = { workspace = true, features = ["backend-postgres"] }
sea-query-postgres = { version = "0.5.0-rc.1", features = [
  "with-chrono",
  "with-json",
  "with-uuid",
] }
tokio.workspace = true
tokio-postgres.workspace = true
uuid.workspace = true
