[package]
name = "colette-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.4", features = ["postgres", "runtime-tokio", "time"] }
time = { version = "0.3.36", features = ["macros"] }
