[package]
name = "colette-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
axum = { version = "0.7.5", default-features = false, features = [
  "http1",
  "macros",
  "multipart",
  "tokio",
] }
axum-embed = { version = "0.1.0", default-features = false }
axum-valid = { version = "0.19.0", default-features = false, features = [
  "422",
  "basic",
  "into_json",
  "validator",
] }
chrono = { workspace = true, features = ["serde"] }
cron = { version = "0.12.1", default-features = false }
colette-backup.workspace = true
colette-config.workspace = true
colette-core.workspace = true
colette-migrations.workspace = true
colette-password.workspace = true
colette-repositories.workspace = true
colette-plugins.workspace = true
colette-scraper.workspace = true
colette-tasks.workspace = true
rust-embed = { version = "8.5.0", default-features = false, features = [
  "interpolate-folder-path",
] }
sea-orm.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http = { version = "0.5.2", default-features = false, features = [
  "cors",
] }
tower-sessions = { version = "0.12.2", default-features = false, features = [
  "axum-core",
] }
tower-sessions-sqlx-store = { version = "0.12.0", default-features = false, features = [
  "postgres",
  "sqlite",
] }
utoipa = { version = "5.0.0-alpha.0", default-features = false, features = [
  "chrono",
  "preserve_order",
  "preserve_path_order",
  "uuid",
] }
utoipa-scalar = { version = "0.2.0-alpha.0", default-features = false, features = [
  "axum",
] }
uuid = { workspace = true, features = ["serde"] }
validator = { version = "0.18.1", default-features = false, features = [
  "derive",
] }
