[package]
name = "colette-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.5", features = ["macros"] }
bytes.workspace = true
chrono.workspace = true
colette-core.workspace = true
colette-password.workspace = true
colette-postgres.workspace = true
colette-scraper.workspace = true
colette-sqlite.workspace = true
rust-embed = "8.4.0"
serde.workspace = true
thiserror.workspace = true
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.5.2", features = ["cors", "fs"] }
tower-sessions = "0.12.2"
tower-sessions-sqlx-store = { version = "0.12.0", features = [
  "postgres",
  "sqlite",
] }
utoipa = { version = "5.0.0-alpha.0", features = [
  "chrono",
  "preserve_order",
  "preserve_path_order",
] }
utoipa-scalar = { version = "0.2.0-alpha.0", features = ["axum"] }
validator = { version = "0.17", features = ["derive"] }
