[package]
name = "colette-tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
chrono.workspace = true
colette-core.workspace = true
cron = { version = "0.12.1", default-features = false }
futures.workspace = true
tokio.workspace = true
