[package]
name = "colette-http"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
http.workspace = true
http-body-util.workspace = true
reqwest.workspace = true
thiserror.workspace = true
