name: Build and Release Binaries

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      APP_NAME: colette-server

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Build web
        run: |
          npm ci
          npm run build

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Setup musl builds
        if: contains(matrix.target, 'musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build binaries
        run: cargo build --release --target ${{ matrix.target }} -p ${{ env.APP_NAME }}
        env:
          SQLX_OFFLINE: true

      - name: Package binaries (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/${{ env.APP_NAME }}.exe dist/
          cd dist
          7z a ${{ env.APP_NAME }}-${{ matrix.target }}.zip ${{ env.APP_NAME }}.exe

      - name: Package binaries (non-Windows)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/${{ env.APP_NAME }} dist/
          cd dist
          tar czf ${{ env.APP_NAME }}-${{ matrix.target }}.tar.gz ${{ env.APP_NAME }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.target }}
          path: |
            dist/*.tar.gz
            dist/*.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          merge-multiple: true

      - name: Release binaries
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
